server: 
  port: 80
  servlet:
    encoding:
      charset: utf-8
      force: true
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://52.79.113.104:3306/mybank
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Backlee99#
  
  #h2:
  #  console:
  #    enabled: true
  #output:
  #  ansi:
  #    enabled: always
  
mybatis: 
 mapper-locations:
  - classpath:mapper/**.xml
 configuration:
   map-underscore-to-camel-case: true 
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   
logging:
  level:
    org.mybatis: DEBUG
    
filePath:
  files: file:/C:/Users/pc-uefi/git/bank/upload/
    